### ISSUE TITLE
Paragraph Title Issue

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#101]
My paragraph titles for the book of Daniel are not the titles that I have submitted in the program. I entered all the titles from Daniel into the program, but when I created my charts, they are not from Daniel, but they are the paragraph titles from the book of Joel and the book of Amos, somehow mixed in with Daniel. I have recreated and saved them a few times, but nothing is fixing the issue. [Attachment.zip](https://sbs-charter.s3-us-west-2.amazonaws.com/issues/Paragraph%20Title%20Issue.zip)

**Comment by TheDude70** [comment]
Unfortunately i am away until next week when i will look into the issue.
