### ISSUE TITLE
Downloading Word Document

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#31]
I am currently trying to download my charts for Colossians as a word document. However when I try to open it, it says that there is an error and illegal character. It work for the pdf, but I can't edit on the pdf. Attached if both the docx and pdf file.[Attachment.zip](https://s3-us-west-2.amazonaws.com/sbs-charter/issues/Downloading%20Word%20Document.zip)

**Comment by TheDude70** [comment]
Thanks for the error report. It was an issue with the & (ampersand) character causing a corrupted file.

Has been fixed. Please download your charts again.
