### ISSUE TITLE
Charts Insides and Outsides

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#35]
Hey Paul, firstly, thank you so much for everything that you're doing with this site! It's seriously been the biggest blessing to us students and has made our lives drastically easier.. you're amazing.. 

But hey so, for the insides and outsides, I used to do them all on the site and it was amazing, but now I'm not able to access the insides or outsides.. yeah, but thanks again for everything!

**Comment by TheDude70** [comment]
All seems to be working on the site. I did not receive a response to my follow-up email, therefore am closing this issue, as I cannot recreate the issue.
