### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#36]
Hahaha yeah so this isn't really a feature request, but just wanted to thank you again just for all the time that you've sacrificed in making this site so amazing and user friendly! I've really noticed the site changing almost daily in it's functionality (most likely a heck of a lot more going on behind the scenes that no one can see) and I really just wanted to thank you on behalf of all the students.. This school has been absolutely amazing so far, the work load came as a bit of a shock to a lot of us, but this site and all that you're doing has given us more time to chart and observe and really get out of the word the riches of what God had waiting there for us. Thank you so much again Paul!

**Comment by TheDude70** [comment]
You are more than welcome, and thanks for the appreciation.
