### ISSUE TITLE
PTs didn't get saved

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#37]
I have pressed "saved" when entering every 5-10 PTs (1st Corinthians) and internet was working fine. But 90% of it was gone after refresh and cannot be retrieved. Hoping they were in the system somehow but it was not the case.

**Comment by TheDude70** [comment]
I have just done a check and there were no system outages in the last hour (I assume the issue occurred just before the ticket was opened). Have on the site entered titles as a test for 1 Cor without any issues. The site also auto saves every 30 seconds.

At the moment I am at loss as to what may have happened. If all was working your end, and all working my end, then it has to have been something out of my control.

That said, I am closing this issue and have opened a new one to add a check for an active connection to the server, which then will display a warning in case the server cannot be reached.
