### ISSUE TITLE
Chart in Word format cannot open

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#44]
Hi there,
I downloaded my charts, which comes in Word and PDF. I do my charts on the Word document, but after downloading, I was not able to open and this window. popped up. I tried 3 times and still cannot open. I can open the PDF though but I am not able to work on it. Any way to find out what's wrong or how to fix? 
Our work for Leviticus is due on Thursday noon. 

Thank you!  
Cherry[Attachment.zip](https://s3-us-west-2.amazonaws.com/sbs-charter/issues/Chart%20in%20Word%20format%20cannot%20open.zip)

**Comment by TheDude70** [comment]
This has now been fixed and using quotes in book title should now generate a correct word file.
