### ISSUE TITLE
Cannot regenerate chart

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#46]
Hi Paul,
Thanks for replying. But now I cannot regenerate the charts... because this popped up on screen instead. 
Sorry to trouble you again! Let me know what I can do? 

Thanks,
Cherry[Attachment.zip](https://s3-us-west-2.amazonaws.com/sbs-charter/issues/Cannot%20regenerate%20chart.zip)

**Comment by TheDude70** [comment]
Bah 😃. Have cleared the cache, could you please try again.
