### ISSUE TITLE
Galatians - Paragraph breaks

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#47]
The following paragraphs breaks does not go as the ESV bible

2:11-21 should be 2;11-16, 2;17-21
3;1-5 should be 3;1-6
3;6-9 should be 3:7-9
6;6 no paragraph 
6;7-10 Should be 6;6-10
[Attachment.zip](https://s3-us-west-2.amazonaws.com/sbs-charter/issues/Galatians%20-%20Paragraph%20breaks.zip)

**Comment by TheDude70** [comment]
Thanks for your submission. At the moment all the paragraph breaks are based on the RSV version, as this app was developed based on the breaks used in Taiwan SBS for both English and Chinese versions.

I am looking at updating the system to handle a few different version's paragraph breaks, including ESV, but this will take some time to sort.
