### ISSUE TITLE
Combined books Key Verse Option

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#52]
So for the book of Samuel, since both books are combined into one. I want to choose a key verse from the 2 Samuel, but there is no way to distinguish the verse in the books.
example. I want to put 2 Samuel 7;16-17, but it will think i mean 1 Samuel 7:16-17

Can there be a way to distinguish between the two books when they are combined. This may be helpful with Kings and Chronicles.

Thank You

**Comment by TheDude70** [comment]
Thanks for you suggestion. This has now been implemented.

Blessings,
Paul
