### ISSUE TITLE
System not saving

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#58]
Hello, I am having trouble saving PT'S. 

"undefined is not an object (evaluating 'this.$refs.key_verse_two.value') " 

This keeps appearing when I try to save my PT'S. I thought it was the wifi at first but it isn't. It appears every time I try to save

**Comment by TheDude70** [comment]
Please ignore my email request for extra info. Have found it was an issue in Microsoft Edge. Have pushed a fix which should have solved the problem.
