### ISSUE TITLE
Galatians Paragraph Break

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#61]
In chapter two of Galatians, there is no break between verses 11-21. There's a clear segment break at verse 15, but no option to put a segment there because of how the PT options are prematurely set up. Also some small indents are not taken into account. (4:21-31 & 6:6 is it's own PT). 
Thanks :)

**Comment by TheDude70** [comment]
Already am working on getting the paragraph breaks for ESV. Currently it uses the RSV breaks which used to be the default for SBS.
