### ISSUE TITLE
Zephaniah Key Verse Errors

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#66]
I think the script for the Key Verse for Zephaniah is incorrectly linked to the wrong book.
I put down 2:3 as the Key Verse and it quoted on the horizontal incorrectly.
It looks like the book may be linked to to Philippians.[Attachment.zip](https://sbs-charter.s3-us-west-2.amazonaws.com/issues/Zephaniah%20Key%20Verse%20Errors.zip)

**Comment by TheDude70** [comment]
Have pushed an update. Please download your charts again, and you should have the correct verse.
