### ISSUE TITLE
Reset PTs for Isaiah

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#77]
Just wrote a message to you and afterwards think I understand what you were trying to say in the red banner across the program (which was very poorly explained for those of us who have no idea what a ticket is)

Can you reset Isaiah for me?

**Comment by TheDude70** [comment]
Have reset your PTs for Isaiah. You should be able to now correctly enter them and set your Seg/Sec/Divs.

Apologies for the time lost and things not totally clear.

Blessings.
