### ISSUE TITLE
PT

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#85]
I need ESV breaks, lost my PT. And keep getting a message of 
"If you are unable to perform actions on the book you are working on due to the reverting back to RSV breaks, then report in an issue including the book you are having problems with. Unfortunately it will mean having to reset any PTs and breaks entered."

**Comment by TheDude70** [comment]
The ESV breaks are disabled for now. Your PTs were reset, meaning you need to re-enter them.
