### ISSUE TITLE
PTs

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#87]
I'm having the following issue with the book of Isaiah:
 - I've filled in all the PTs for the book, set my breaks, added a title and key verse but the PTs for 1:1-19:18; the title; the key verse all refuse to save.
- The error message displayed is "undefined is not an object (evaluating 'app.$refs["paragraph_title_"+e.id].value=e.title')"[Attachment.zip](https://sbs-charter.s3-us-west-2.amazonaws.com/issues/PTs.zip)

**Comment by TheDude70** [comment]
Not sure how, but somehow you had extra PTs that should not have been part of Isaiah. Have removed the extra PTs in question and you should now be able to generate the charts. However there is an issue with the Amazon server where currently we can't get the books to download, which I am looking into.
