### ISSUE TITLE
Chinese version

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#90]
Dear Paul
Firstly I would like to say that you have done an amazing job with your charting software. I work with the SBS's in China where we use a Visual Basic version of your software for our students. I am also busy translating and leading the Chinese version of the OnlineSBS. Yesterday I was evaluating the charting options currently being used by the OnlineSBS as we need to choose what to do for the Chinese version.
I like your version the best and want to know if you would like to work together in making both the online and offline versions of the software available to all students that will be doing the SBS in Chinese? I will be able to do any translation work that would still needs to be done.
God bless
Herman

**Comment by TheDude70** [comment]
CUV PT breaks and basic simplified Chinese site language has been implemented
