### ISSUE TITLE
Missing Paragraph

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#91]
Missing paragraph at 1 Peter 3:18

**Comment by TheDude70** [comment]
Thanks for your feedback.

The current breaks are based on the RSV and based on what is/has been used by SBS until RSV went out of print, and can't modify it as already many have their charts based on those breaks.

Am working on adding more versions (ESV, NRSV,..) to bring it up to date with versions that are used in many SBS's around the world, which will have more PT breaks.
