### ISSUE TITLE
Lowest level PT

### ISSUE THREAD

**Issue by TheDude70Dev** [TheDude70/sbs-charter#92]
Allow the paragraph titles, instead of sections to be the lowest level in the horizontal for small books such as Titus and 1 Peter and so on...

**Comment by TheDude70** [comment]
When no **_Segments_** are defined then PTs are the lowest on the horizontal, as per SBS instructions. If there are to be breaks, then always start with Divisions, then Sections, then Segments. From looking at your current input it appears you are adding Segments instead of Divisions.
